<?php

namespace Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-03 at 08:10:25.
 */
class HttpRequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HttpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $get=array(
            'var' => 'val',
            'choice' => 1,
            
        );
        $post=array(
            'key' =>'value',
            'test' =>1,
        );
        $server=array(
            'USER_AGENT' => 'firefox',
            'REQUEST_METHOD' => 'GET',
        );
        $this->object =  HttpRequest::create($get, $post, $server);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Util\HttpRequest::createFromGlobals
     * @todo   Implement testCreateFromGlobals().
     */
    public function testCreateFromGlobals() {
        // Remove the following lines when you implement this test.
       $_GET['test1'] = 'test'; 
       $_POST['test2'] = 'test2'; 
       $_SERVER['test3'] = 'test3';
       
       $request = HttpRequest::createFromGlobals();
       
       $this->assertAttributeContains('test', 'get', $request);
       $this->assertAttributeContains('test2', 'post', $request);
       $this->assertAttributeContains('test3', 'server', $request);
       
    }

    /**
     * @covers Util\HttpRequest::create
     * @covers Util\HttpRequest::__construct
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        
        $get=array(
            'var' => 'val',
            'choice' => 1,
            
        );
        $post=array(
            'key' =>'value',
            'test' =>1,
        );
        $server=array(
            'USER_AGENT' => 'firefox'
        );
        $object = HttpRequest::create($get, $post, $server);
        
        $this->assertInstanceOf('Util\HttpRequest', $object);
        
        $this->assertAttributeContains('val', 'get', $object);
        $this->assertAttributeContains('value', 'post', $object);
        $this->assertAttributeContains('firefox', 'server', $object);
        
    }

    /**
     * @covers Util\HttpRequest::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        
        $this->assertEquals('value', $this->object->get('key'));
        $this->assertEquals('val', $this->object->get('var'));
        $this->assertEmpty($this->object->get('baz'));
        $this->assertEmpty($this->object->get('USER_AGENT'));
    }

    /**
     * @covers Util\HttpRequest::getGetParameter
     * @todo   Implement testGetGetParameter().
     */
    public function testGetGetParameter() {
        
        $this->assertEquals(1, $this->object->getGetParameter('choice'));
        $this->assertEquals('val', $this->object->getGetParameter('var'));
        $this->assertEmpty($this->object->getGetParameter('baz'));
        $this->assertEmpty($this->object->getGetParameter('USER_AGENT'));
    }

    /**
     * @covers Util\HttpRequest::getPostParameter
     * @todo   Implement testGetPostParameter().
     */
    public function testGetPostParameter() {
        $this->assertEquals('value', $this->object->getPostParameter('key'));
        $this->assertEquals(false, $this->object->getPostParameter('fake_key'));
        $this->assertEmpty($this->object->getPostParameter('baz'));
    }

    /**
     * @covers Util\HttpRequest::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader() {
       $this->assertEquals('firefox', $this->object->getHeader('USER_AGENT')); 
       $this->assertEquals('firefox', $this->object->getHeader('user_agent')); 
       $this->assertEmpty($this->object->getHeader('baz'));
    }

    /**
     * @covers Util\HttpRequest::isMethod
     * @todo   Implement testGetHeader().
     */
    public function testIsMethod() {
       
       $this->assertTrue($this->object->isMethod('get'));
       $this->assertFalse($this->object->isMethod('post'));
    }

}
