<?php

namespace Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-03 at 08:10:25.
 */
class HttpRequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HttpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $get=array(
            'var' => 'val',
            'choice' => 1,
            
        );
        $post=array(
            'key' =>'value',
            'test' =>1,
        );
        $server=array(
            'USER_AGENT' => 'firefox'
        );
        $this->object =  HttpRequest::create($get, $post, $server);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Util\HttpRequest::createFromGlobals
     * @todo   Implement testCreateFromGlobals().
     */
    public function testCreateFromGlobals() {
        // Remove the following lines when you implement this test.
        
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Util\HttpRequest::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        
        $get=array(
            'var' => 'val',
            'choice' => 1,
            
        );
        $post=array(
            'key' =>'value',
            'test' =>1,
        );
        $server=array(
            'USER_AGENT' => 'firefox'
        );
        $object = HttpRequest::create($get, $post, $server);
        
        $this->assertInstanceOf('Util\HttpRequest', $object);
        
        $this->assertAttributeContains('val', 'get', $object);
        $this->assertAttributeContains('value', 'post', $object);
        $this->assertAttributeContains('firefox', 'server', $object);
        
    }

    /**
     * @covers Util\HttpRequest::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        
        $this->assertEquals('value', $this->object->get('key'));
        $this->assertEquals('val', $this->object->get('var'));
        $this->assertEmpty($this->object->get('baz'));
        $this->assertEmpty($this->object->get('USER_AGENT'));
    }

    /**
     * @covers Util\HttpRequest::getGetParameter
     * @todo   Implement testGetGetParameter().
     */
    public function testGetGetParameter() {
        
        $this->assertEquals('value', $this->object->get('key'));
        $this->assertEquals('val', $this->object->get('var'));
        $this->assertEmpty($this->object->get('baz'));
        $this->assertEmpty($this->object->get('USER_AGENT'));
    }

    /**
     * @covers Util\HttpRequest::getPostParameter
     * @todo   Implement testGetPostParameter().
     */
    public function testGetPostParameter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Util\HttpRequest::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
