<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-02 at 08:26:13.
 */
class RockTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Rock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Rock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
